config/routes.rb
Rails.application.routes.draw do
  resources :articals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artical.rb
class Artical < ApplicationRecord
end

app/controllers/api/v1/articals_controller.rb
class ArticalsController < ApplicationController
  before_action :set_artical, only: [:show, :edit, :update, :destroy]

  # GET /articals
  # GET /articals.json
  def index
    @articals = Artical.all
  end

  # GET /articals/1
  # GET /articals/1.json
  def show
  end

  # GET /articals/new
  def new
    @artical = Artical.new
  end

  # GET /articals/1/edit
  def edit
  end

  # POST /articals
  # POST /articals.json
  def create
    @artical = Artical.new(artical_params)

    respond_to do |format|
      if @artical.save
        # format.html { redirect_to @artical, notice: 'Artical was successfully created.' }
        render json: @artical 
      else
        format.html { render :new }
        format.json { render json: @artical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articals/1
  # PATCH/PUT /articals/1.json
  def update
    respond_to do |format|
      if @artical.update(artical_params)
        format.html { redirect_to @artical, notice: 'Artical was successfully updated.' }
        format.json { render :show, status: :ok, location: @artical }
      else
        format.html { render :edit }
        format.json { render json: @artical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articals/1
  # DELETE /articals/1.json
  def destroy
    @artical.destroy
    respond_to do |format|
      format.html { redirect_to articals_url, notice: 'Artical was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artical
      @artical = Artical.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artical_params
      params.require(:artical).permit(:title, :content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 protect_from_forgery with: :null_session
end

app/controllers/articals_controller.rb
class ArticalsController < ApplicationController

  # before_action  only: [:show, :edit, :update, :destroy]

  # GET /articals
  # GET /articals.json
  def index
    @articals = Artical.where('title !=?',"")

    render json: @articals
  end

  # GET /articals/1
  # GET /articals/1.json
  def show
  end

  # GET /articals/new
  def new
    @artical = Artical.new
    render json: @articals
  end

  # GET /articals/1/edit
  def edit
  end

  # POST /articals
  # POST /articals.json
  def create
    # binding.pry
    @artical = Artical.new(title: params[:title],content: params[:content])
    @artical.save
    render json: @artical
  end

  # PATCH/PUT /articals/1
  # PATCH/PUT /articals/1.json
  def update
    # binding.pry
    @artical=Artical.find(params[:id])
    @artical.update_columns(enable: params[:enable])
    render json: @artical
    # respond_to do |format|
    #   if @artical.update(artical_params)
    #     format.html { redirect_to @artical, notice: 'Artical was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @artical }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @artical.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /articals/1
  # DELETE /articals/1.json
  def destroy
    # binding.pry
    @artical=Artical.find(params[:id])
    @artical.destroy
    render json: @artical
      # format.json { head :no_content }
    
  end

  private
    # binding.pry
    # Use callbacks to share common setup or constraints between actions.
    def set_artical
      @artical = Artical.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artical_params
      params.require(:artical).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articals_helper.rb
module ArticalsHelper
end

app/views/articals/_form.html.erb
<%= form_with(model: artical, local: true) do |form| %>
  <% if artical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artical.errors.count, "error") %> prohibited this artical from being saved:</h2>

      <ul>
      <% artical.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articals/edit.html.erb
<h1>Editing Artical</h1>

<%= render 'form', artical: @artical %>

<%= link_to 'Show', @artical %> |
<%= link_to 'Back', articals_path %>

app/views/articals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articals.each do |artical| %>
      <tr>
        <td><%= artical.title %></td>
        <td><%= artical.content %></td>
        <td><%= link_to 'Show', artical %></td>
        <td><%= link_to 'Edit', edit_artical_path(artical) %></td>
        <td><%= link_to 'Destroy', artical, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artical', new_artical_path %>

app/views/articals/new.html.erb
<h1>New Artical</h1>

<%= render 'form', artical: @artical %>

<%= link_to 'Back', articals_path %>

app/views/articals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @artical.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @artical.content %>
</p>

<%= link_to 'Edit', edit_artical_path(@artical) %> |
<%= link_to 'Back', articals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailApiPro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>